
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.ListSelectionModel;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Home pc
 */
public class changinOrderOfSongsOfPlaylist extends javax.swing.JFrame {

   
   DefaultListModel newSongLIstModel; 
   DefaultListModel songLists ; 
    DefaultListModel playListModel;
    String playerName;
    PlayList pList;
    int num;
    public changinOrderOfSongsOfPlaylist(User user,String playerName) {
        initComponents();
        playListSongs.setSelectionMode(
                    ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        num=0;
        playListNameLabel.setText(playerName);
        this.playerName = playerName;
        playListModel = new DefaultListModel();
        for(int i=0;i<HomePage.user.getPlayLists().size();i++){
            if(HomePage.user.getPlayLists().get(i).getTitle().equals(playerName)){
                num = i;
                for(int j=0;j<HomePage.user.getPlayLists().get(i).getSongs().size();j++){
                    playListModel.addElement(HomePage.user.getPlayLists().get(i).getSongs().get(j).getTitle());         
                }
                break;
            }
        playListSongs.setModel(playListModel);
        
        }
        pList = HomePage.user.getPlayLists().get(num);
        songLists = new DefaultListModel(); 
        for(int i=0;i<user.getSongs().size();i++){
            songLists.addElement(user.getSongs().get(i).getTitle());
        }
        songsList.setModel(songLists);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        changeButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        playListSongs = new javax.swing.JList<>();
        playListNameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        songs = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        songsList = new javax.swing.JList<>();
        addButton = new javax.swing.JButton();
        rename = new javax.swing.JButton();
        nameText = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        changeButton.setText("->>");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        saveButton.setText("save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(playListSongs);

        playListNameLabel.setText("playlist");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playListNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(playListNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("editing play list song");

        songs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        songs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        songs.setText("your songs");

        jScrollPane3.setViewportView(songsList);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(songs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(songs, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane4.setViewportView(jPanel3);

        addButton.setText("add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        rename.setText("rename");
        rename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(409, 409, 409))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveButton)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(changeButton)
                                        .addGap(33, 33, 33)
                                        .addComponent(jt1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(145, 145, 145)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rename))
                                    .addComponent(addButton))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton)
                    .addComponent(changeButton)
                    .addComponent(jt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(rename)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed

        
        String tewx=jt1.getText();
        String[] subs=new String[2];
        subs=tewx.split("-");
        for(int i=0;i<2;i++){
            System.out.println(subs[i]);
        }
        Music m1=pList.getSongs().get((Integer.parseInt(subs[0]))-1);
        Music m2=pList.getSongs().get((Integer.parseInt(subs[1]))-1);

        ArrayList<Music> musics=new ArrayList<>();
//
        for (int i = 0; i <pList.getSongs().size() ; i++) {
            if (i==(Integer.parseInt(subs[0]))-1)
                musics.add(m2);
            else if (i==(Integer.parseInt(subs[1]))-1)
                musics.add(m1);
            else
            musics.add(i,pList.getSongs().get(i));
        }

        pList.setSongs(musics);


        ArrayList<PlayList> pls=new ArrayList<>();
        for (int i = 0; i <HomePage.user.getPlayLists().size() ; i++) {
            if (i!=num)
                pls.add(HomePage.user.getPlayLists().get(i));
            else pls.add(pList);
        }

        HomePage.user.getPlayLists().add(num,pList);
        for (int i = 0; i < pList.getSongs().size(); i++) {

            System.out.println(pList.getSongs().get(i).getTitle());

        }

        pList.setSongs(musics);

//        playListSongs.setSelectionMode(
//                ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
//        int value1 = playListSongs.getSelectedIndex();
//        String pName = playListSongs.getSelectedValue();
//        ArrayList<String> values=new ArrayList<>();
//        ArrayList<Integer> indexes=new ArrayList<>();
//        while(values.size()<=2){
//            if (!indexes.contains(playListSongs.getSelectedIndex())){
//                indexes.add(playListSongs.getSelectedIndex());
//                values.add(playListSongs.getSelectedValue());
//            }
//        }

//        System.out.println("llllllllllllllllllllllllllll"+values)tModel);
      //  playListSongs.setModel(playListModel);
      

    }//GEN-LAST:event_changeButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
         PlayList s = new PlayList(playerName);
        for(int i=0;i<pList.getSongs().size();i++){
            s.addSong(getMusic((String) playListModel.get(i)));
        }
        HomePage.user.getPlayLists().remove(num);
        HomePage.user.getPlayLists().add(s);
        for(int i=0;i<HomePage.user.getPlayLists().size();i++){
            if(HomePage.user.getPlayLists().get(i).getTitle().equals(playerName)){
                num = i;
                break;
            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int value = playListSongs.getSelectedIndex();
        playListModel.remove(value);
        playListSongs.setModel(playListModel);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        int value = songsList.getSelectedIndex();
        String name = songsList.getSelectedValue();
        System.out.println("name"+name);
        playListModel.addElement(name);
        playListSongs.setModel(playListModel);
        Music m = null;
        System.out.println("bhhh"+HomePage.user.getPlayLists().get(num).getSongs().size());
        for(int i=0;i<HomePage.user.getSongs().size();i++){
            if(HomePage.user.getSongs().get(i).getTitle().equals(name)){
               
                m = HomePage.user.getSongs().get(i); 
                System.out.println("iiiiiiiiiiiiiii");
                break;
            }
        }
        if (!HomePage.user.getPlayLists().get(num).getSongs().contains(m))
        HomePage.user.getPlayLists().get(num).addSong(m);
    }//GEN-LAST:event_addButtonActionPerformed

    private void renameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameActionPerformed
        String n = nameText.getText();
        HomePage.user.getPlayLists().get(num).setTitle(n);
        playListNameLabel.setText(n);
        playerName = n;
        
         playListModel = new DefaultListModel();
        for(int i=0;i<HomePage.user.getPlayLists().size();i++){
            if(HomePage.user.getPlayLists().get(i).getTitle().equals(playerName)){
                num = i;
                for(int j=0;j<HomePage.user.getPlayLists().get(i).getSongs().size();j++){
                    playListModel.addElement(HomePage.user.getPlayLists().get(i).getSongs().get(j).getTitle());         
                }
                break;
            }
        playListSongs.setModel(playListModel);
        
    }//GEN-LAST:event_renameActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public Music getMusic(String name){
        Music music = null;
        for(int i=0;i<pList.getSongs().size();i++){
            if(pList.getSongs().get(i).getTitle().equals(name)){
                music =  pList.getSongs().get(i);
            }
        }
        return music;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changinOrderOfSongsOfPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changinOrderOfSongsOfPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changinOrderOfSongsOfPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changinOrderOfSongsOfPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changinOrderOfSongsOfPlaylist(HomePage.user,HomePage.playerSelected).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton changeButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jt1;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel playListNameLabel;
    private javax.swing.JList<String> playListSongs;
    private javax.swing.JButton rename;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel songs;
    private javax.swing.JList<String> songsList;
    // End of variables declaration//GEN-END:variables
}
